project_id = "aneazkhnqkkpqtcxunqd"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-notification]
    verify_jwt = false
  [functions.send-recovery-email]
    verify_jwt = false
  [functions.check-auth-health]
    verify_jwt = false
