import { usePermissionsContext } from "@/contexts/PermissionsContext";
import { getModuleLabel } from "@/lib/moduleLabels";

// All permission keys in the system
export const ALL_PERMISSION_KEYS = [
  "dashboard.view",
  "customers.view", "customers.create", "customers.edit", "customers.delete", "customers.export",
  "leads.view", "leads.create", "leads.edit", "leads.delete",
  "bookings.view", "bookings.create", "bookings.edit", "bookings.delete", "bookings.approve",
  "quotations.view", "quotations.create", "quotations.edit", "quotations.delete",
  "tour_packages.view", "tour_packages.create", "tour_packages.edit", "tour_packages.delete",
  "itineraries.view", "itineraries.create", "itineraries.edit", "itineraries.delete",
  "accommodations.view", "accommodations.create", "accommodations.edit", "accommodations.delete",
  "suppliers.view", "suppliers.create", "suppliers.edit", "suppliers.delete",
  "contracts.view", "contracts.create", "contracts.edit", "contracts.delete", "contracts.approve",
  "payments.view", "payments.create", "payments.edit", "payments.delete",
  "staff.view", "staff.create", "staff.edit", "staff.delete",
  "leave.view", "leave.create", "leave.approve",
  "payroll.view", "payroll.create", "payroll.edit",
  "finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve",
  "workflow.view", "workflow.create",
  "settings.view", "settings.edit",
  "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit", "raw_contacts.delete",
  "b2b_tours.view", "b2b_tours.logs",
  "candidates.view", "candidates.create", "candidates.edit", "candidates.delete",
  "kpi_policies.view", "kpi_policies.create", "kpi_policies.edit",
] as const;

export type PermissionKey = typeof ALL_PERMISSION_KEYS[number];

// Permission groups for UI display
// Labels lấy từ src/lib/moduleLabels.ts (single source of truth).
export const PERMISSION_GROUPS: Record<string, { label: string; keys: PermissionKey[] }> = {
  dashboard: { label: getModuleLabel("dashboard"), keys: ["dashboard.view"] },
  customers: { label: getModuleLabel("customers"), keys: ["customers.view", "customers.create", "customers.edit", "customers.delete", "customers.export"] },
  leads: { label: getModuleLabel("leads"), keys: ["leads.view", "leads.create", "leads.edit", "leads.delete"] },
  bookings: { label: getModuleLabel("bookings"), keys: ["bookings.view", "bookings.create", "bookings.edit", "bookings.delete", "bookings.approve"] },
  quotations: { label: getModuleLabel("quotations"), keys: ["quotations.view", "quotations.create", "quotations.edit", "quotations.delete"] },
  tour_packages: { label: getModuleLabel("tour_packages"), keys: ["tour_packages.view", "tour_packages.create", "tour_packages.edit", "tour_packages.delete"] },
  itineraries: { label: getModuleLabel("itineraries"), keys: ["itineraries.view", "itineraries.create", "itineraries.edit", "itineraries.delete"] },
  accommodations: { label: getModuleLabel("accommodations"), keys: ["accommodations.view", "accommodations.create", "accommodations.edit", "accommodations.delete"] },
  suppliers: { label: getModuleLabel("suppliers"), keys: ["suppliers.view", "suppliers.create", "suppliers.edit", "suppliers.delete"] },
  contracts: { label: getModuleLabel("contracts"), keys: ["contracts.view", "contracts.create", "contracts.edit", "contracts.delete", "contracts.approve"] },
  payments: { label: getModuleLabel("payments"), keys: ["payments.view", "payments.create", "payments.edit", "payments.delete"] },
  staff: { label: getModuleLabel("staff"), keys: ["staff.view", "staff.create", "staff.edit", "staff.delete"] },
  leave: { label: getModuleLabel("leave"), keys: ["leave.view", "leave.create", "leave.approve"] },
  payroll: { label: getModuleLabel("payroll"), keys: ["payroll.view", "payroll.create", "payroll.edit"] },
  finance: { label: getModuleLabel("finance"), keys: ["finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve"] },
  workflow: { label: getModuleLabel("workflow"), keys: ["workflow.view", "workflow.create"] },
  settings: { label: getModuleLabel("settings"), keys: ["settings.view", "settings.edit"] },
  raw_contacts: { label: getModuleLabel("raw_contacts"), keys: ["raw_contacts.view", "raw_contacts.create", "raw_contacts.edit", "raw_contacts.delete"] },
  b2b_tours: { label: getModuleLabel("b2b_tours"), keys: ["b2b_tours.view", "b2b_tours.logs"] },
};

// Scope rules
export type ScopeLevel = "all" | "department" | "personal";

// Default permissions per role (client-side mirror of DB function)
const DEFAULT_PERMISSIONS: Record<string, PermissionKey[]> = {
  ADMIN: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit", "customers.delete", "customers.export",
    "leads.view", "leads.create", "leads.edit", "leads.delete",
    "bookings.view", "bookings.create", "bookings.edit", "bookings.delete", "bookings.approve",
    "quotations.view", "quotations.create", "quotations.edit", "quotations.delete",
    "tour_packages.view", "tour_packages.create", "tour_packages.edit", "tour_packages.delete",
    "itineraries.view", "itineraries.create", "itineraries.edit", "itineraries.delete",
    "accommodations.view", "accommodations.create", "accommodations.edit", "accommodations.delete",
    "suppliers.view", "suppliers.create", "suppliers.edit", "suppliers.delete",
    "contracts.view", "contracts.create", "contracts.edit", "contracts.delete", "contracts.approve",
    "payments.view", "payments.create", "payments.edit", "payments.delete",
    "staff.view", "staff.create", "staff.edit", "staff.delete",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve",
    "workflow.view", "workflow.create",
    "settings.view", "settings.edit",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit", "raw_contacts.delete",
    "b2b_tours.view", "b2b_tours.logs",
  ],
  SUPER_ADMIN: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit", "customers.delete", "customers.export",
    "leads.view", "leads.create", "leads.edit", "leads.delete",
    "bookings.view", "bookings.create", "bookings.edit", "bookings.delete", "bookings.approve",
    "quotations.view", "quotations.create", "quotations.edit", "quotations.delete",
    "tour_packages.view", "tour_packages.create", "tour_packages.edit", "tour_packages.delete",
    "itineraries.view", "itineraries.create", "itineraries.edit", "itineraries.delete",
    "accommodations.view", "accommodations.create", "accommodations.edit", "accommodations.delete",
    "suppliers.view", "suppliers.create", "suppliers.edit", "suppliers.delete",
    "contracts.view", "contracts.create", "contracts.edit", "contracts.delete", "contracts.approve",
    "payments.view", "payments.create", "payments.edit", "payments.delete",
    "staff.view", "staff.create", "staff.edit", "staff.delete",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve",
    "workflow.view", "workflow.create",
    "settings.view", "settings.edit",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit", "raw_contacts.delete",
    "b2b_tours.view", "b2b_tours.logs",
  ],
  GDKD: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create", "bookings.edit", "bookings.approve",
    "quotations.view", "quotations.create", "quotations.edit",
    "tour_packages.view", "tour_packages.create",
    "itineraries.view", "itineraries.create",
    "contracts.view", "contracts.approve",
    "payments.view", "payments.create",
    "staff.view", "staff.create", "staff.edit",
    "leave.view", "leave.approve",
    "payroll.view",
    "finance.view", "finance.edit", "finance.submit",
    "workflow.view", "workflow.create",
    "settings.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view", "b2b_tours.logs",
  ],
  MANAGER: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create", "bookings.edit",
    "quotations.view", "quotations.create", "quotations.edit",
    "tour_packages.view", "tour_packages.create",
    "itineraries.view", "itineraries.create",
    "contracts.view", "contracts.approve",
    "payments.view", "payments.create",
    "staff.view",
    "leave.view", "leave.approve",
    "payroll.view",
    "finance.view", "finance.submit",
    "workflow.view", "workflow.create",
    "settings.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view", "b2b_tours.logs",
  ],
  DIEUHAN: [
    "dashboard.view",
    "customers.view", "customers.create",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create", "bookings.edit", "bookings.approve",
    "quotations.view", "quotations.create", "quotations.edit",
    "tour_packages.view", "tour_packages.create", "tour_packages.edit",
    "itineraries.view", "itineraries.create", "itineraries.edit",
    "accommodations.view", "accommodations.create", "accommodations.edit",
    "contracts.view", "contracts.approve",
    "payments.view",
    "finance.view", "finance.create", "finance.submit",
    "workflow.view", "workflow.create",
    "suppliers.view",
    "staff.view",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view",
    "settings.view",
    "raw_contacts.view",
    "b2b_tours.view", "b2b_tours.logs",
  ],
  HR_MANAGER: [
    "dashboard.view",
    "staff.view", "staff.create", "staff.edit",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.view", "finance.create", "finance.submit", "finance.approve",
    "settings.view",
    "workflow.view", "workflow.create",
    "tour_packages.view",
    "contracts.view", "contracts.create", "contracts.edit",
    "payments.view",
    "suppliers.view",
  ],
  KETOAN: [
    "dashboard.view",
    "customers.view",
    "bookings.view",
    "quotations.view",
    "itineraries.view",
    "contracts.view",
    "payments.view", "payments.create", "payments.edit",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve",
    "settings.view",
    "workflow.view", "workflow.create",
    "suppliers.view", "suppliers.create",
    "staff.view",
    "leave.view", "leave.create",
    "b2b_tours.view", "b2b_tours.logs",
  ],
  MKT: [
    "dashboard.view",
    "leads.view", "leads.create", "leads.edit",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
  ],
  HCNS: [
    "dashboard.view",
    "staff.view", "staff.create", "staff.edit",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.create", "finance.submit",
    "settings.view",
    "workflow.view", "workflow.create",
    "contracts.view", "contracts.create", "contracts.edit",
    "payments.view",
    "suppliers.view",
  ],
  SALE_DOMESTIC: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view",
  ],
  SALE_INBOUND: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view",
  ],
  SALE_OUTBOUND: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view",
  ],
  SALE_MICE: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view",
  ],
  TOUR: [
    "dashboard.view",
    "customers.view",
    "bookings.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
  ],
  INTERN_SALE_DOMESTIC: [
    "dashboard.view",
    "settings.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view",
  ],
  INTERN_SALE_OUTBOUND: [
    "dashboard.view",
    "settings.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view",
  ],
  INTERN_SALE_MICE: [
    "dashboard.view",
    "settings.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view",
  ],
  INTERN_SALE_INBOUND: [
    "dashboard.view",
    "settings.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
    "b2b_tours.view",
  ],
  INTERN_DIEUHAN: [
    "dashboard.view",
    "settings.view",
    "bookings.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "b2b_tours.view",
  ],
  INTERN_MKT: [
    "dashboard.view",
    "settings.view",
    "leads.view", "leads.create", "leads.edit",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "b2b_tours.view",
  ],
  INTERN_HCNS: [
    "dashboard.view",
    "settings.view",
    "staff.view",
    "leave.view", "leave.create",
    "workflow.view",
    "payroll.view",
  ],
  INTERN_KETOAN: [
    "dashboard.view",
    "settings.view",
    "bookings.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "b2b_tours.view",
  ],
};

export function getDefaultPermissions(role: string): PermissionKey[] {
  return DEFAULT_PERMISSIONS[role] || [];
}

// Re-export from context - this is now the main hook
export function usePermissions() {
  return usePermissionsContext();
}
