import { usePermissionsContext } from "@/contexts/PermissionsContext";

// All permission keys in the system
export const ALL_PERMISSION_KEYS = [
  "dashboard.view",
  "customers.view", "customers.create", "customers.edit", "customers.delete", "customers.export",
  "leads.view", "leads.create", "leads.edit", "leads.delete",
  "bookings.view", "bookings.create", "bookings.edit", "bookings.delete", "bookings.approve",
  "quotations.view", "quotations.create", "quotations.edit", "quotations.delete",
  "tour_packages.view", "tour_packages.create", "tour_packages.edit", "tour_packages.delete",
  "itineraries.view", "itineraries.create", "itineraries.edit", "itineraries.delete",
  "accommodations.view", "accommodations.create", "accommodations.edit", "accommodations.delete",
  "suppliers.view", "suppliers.create", "suppliers.edit", "suppliers.delete",
  "contracts.view", "contracts.create", "contracts.edit", "contracts.delete", "contracts.approve",
  "payments.view", "payments.create", "payments.edit", "payments.delete",
  "staff.view", "staff.create", "staff.edit", "staff.delete",
  "leave.view", "leave.create", "leave.approve",
  "payroll.view", "payroll.create", "payroll.edit",
  "finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve",
  "workflow.view", "workflow.create",
  "settings.view", "settings.edit",
  "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit", "raw_contacts.delete",
] as const;

export type PermissionKey = typeof ALL_PERMISSION_KEYS[number];

// Permission groups for UI display
export const PERMISSION_GROUPS: Record<string, { label: string; keys: PermissionKey[] }> = {
  dashboard: { label: "Tổng quan", keys: ["dashboard.view"] },
  customers: { label: "Khách hàng", keys: ["customers.view", "customers.create", "customers.edit", "customers.delete", "customers.export"] },
  leads: { label: "Tiềm năng", keys: ["leads.view", "leads.create", "leads.edit", "leads.delete"] },
  bookings: { label: "Đặt tour", keys: ["bookings.view", "bookings.create", "bookings.edit", "bookings.delete", "bookings.approve"] },
  quotations: { label: "Báo giá", keys: ["quotations.view", "quotations.create", "quotations.edit", "quotations.delete"] },
  tour_packages: { label: "Gói tour", keys: ["tour_packages.view", "tour_packages.create", "tour_packages.edit", "tour_packages.delete"] },
  itineraries: { label: "Lịch trình", keys: ["itineraries.view", "itineraries.create", "itineraries.edit", "itineraries.delete"] },
  accommodations: { label: "Lưu trú", keys: ["accommodations.view", "accommodations.create", "accommodations.edit", "accommodations.delete"] },
  suppliers: { label: "Nhà cung cấp", keys: ["suppliers.view", "suppliers.create", "suppliers.edit", "suppliers.delete"] },
  contracts: { label: "Hợp đồng", keys: ["contracts.view", "contracts.create", "contracts.edit", "contracts.delete", "contracts.approve"] },
  payments: { label: "Thanh toán", keys: ["payments.view", "payments.create", "payments.edit", "payments.delete"] },
  staff: { label: "Nhân sự", keys: ["staff.view", "staff.create", "staff.edit", "staff.delete"] },
  leave: { label: "Nghỉ phép", keys: ["leave.view", "leave.create", "leave.approve"] },
  payroll: { label: "Bảng lương", keys: ["payroll.view", "payroll.create", "payroll.edit"] },
  finance: { label: "Tài chính", keys: ["finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve"] },
  workflow: { label: "Quy trình", keys: ["workflow.view", "workflow.create"] },
  settings: { label: "Cài đặt", keys: ["settings.view", "settings.edit"] },
  raw_contacts: { label: "Kho Data", keys: ["raw_contacts.view", "raw_contacts.create", "raw_contacts.edit", "raw_contacts.delete"] },
};

// Scope rules
export type ScopeLevel = "all" | "department" | "personal";

// Default permissions per role (client-side mirror of DB function)
const DEFAULT_PERMISSIONS: Record<string, PermissionKey[]> = {
  ADMIN: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit", "customers.delete", "customers.export",
    "leads.view", "leads.create", "leads.edit", "leads.delete",
    "bookings.view", "bookings.create", "bookings.edit", "bookings.delete", "bookings.approve",
    "quotations.view", "quotations.create", "quotations.edit", "quotations.delete",
    "tour_packages.view", "tour_packages.create", "tour_packages.edit", "tour_packages.delete",
    "itineraries.view", "itineraries.create", "itineraries.edit", "itineraries.delete",
    "accommodations.view", "accommodations.create", "accommodations.edit", "accommodations.delete",
    "suppliers.view", "suppliers.create", "suppliers.edit", "suppliers.delete",
    "contracts.view", "contracts.create", "contracts.edit", "contracts.delete", "contracts.approve",
    "payments.view", "payments.create", "payments.edit", "payments.delete",
    "staff.view", "staff.create", "staff.edit", "staff.delete",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve",
    "workflow.view", "workflow.create",
    "settings.view", "settings.edit",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit", "raw_contacts.delete",
  ],
  SUPER_ADMIN: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit", "customers.delete", "customers.export",
    "leads.view", "leads.create", "leads.edit", "leads.delete",
    "bookings.view", "bookings.create", "bookings.edit", "bookings.delete", "bookings.approve",
    "quotations.view", "quotations.create", "quotations.edit", "quotations.delete",
    "tour_packages.view", "tour_packages.create", "tour_packages.edit", "tour_packages.delete",
    "itineraries.view", "itineraries.create", "itineraries.edit", "itineraries.delete",
    "accommodations.view", "accommodations.create", "accommodations.edit", "accommodations.delete",
    "suppliers.view", "suppliers.create", "suppliers.edit", "suppliers.delete",
    "contracts.view", "contracts.create", "contracts.edit", "contracts.delete", "contracts.approve",
    "payments.view", "payments.create", "payments.edit", "payments.delete",
    "staff.view", "staff.create", "staff.edit", "staff.delete",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve",
    "workflow.view", "workflow.create",
    "settings.view", "settings.edit",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit", "raw_contacts.delete",
  ],
  GDKD: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create", "bookings.edit", "bookings.approve",
    "quotations.view", "quotations.create", "quotations.edit",
    "tour_packages.view", "tour_packages.create",
    "itineraries.view", "itineraries.create",
    "contracts.view", "contracts.approve",
    "payments.view", "payments.create",
    "staff.view", "staff.create", "staff.edit",
    "leave.view", "leave.approve",
    "payroll.view",
    "finance.view", "finance.edit", "finance.submit",
    "workflow.view", "workflow.create",
    "settings.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  MANAGER: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create", "bookings.edit",
    "quotations.view", "quotations.create", "quotations.edit",
    "tour_packages.view", "tour_packages.create",
    "itineraries.view", "itineraries.create",
    "contracts.view", "contracts.approve",
    "payments.view", "payments.create",
    "staff.view",
    "leave.view", "leave.approve",
    "payroll.view",
    "finance.view", "finance.submit",
    "workflow.view", "workflow.create",
    "settings.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  DIEUHAN: [
    "dashboard.view",
    "customers.view", "customers.create",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create", "bookings.edit", "bookings.approve",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view", "contracts.approve",
    "payments.view",
    "finance.view", "finance.create", "finance.submit",
    "workflow.view", "workflow.create",
    "suppliers.view",
    "staff.view",
    "leave.view", "leave.create",
    "payroll.view",
  ],
  HR_MANAGER: [
    "dashboard.view",
    "staff.view", "staff.create", "staff.edit",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.view", "finance.create", "finance.submit", "finance.approve",
    "settings.view",
    "workflow.view", "workflow.create",
    "tour_packages.view",
    "contracts.view", "contracts.create", "contracts.edit",
    "payments.view",
    "suppliers.view",
  ],
  KETOAN: [
    "dashboard.view",
    "customers.view",
    "bookings.view",
    "quotations.view",
    "itineraries.view",
    "contracts.view",
    "payments.view", "payments.create", "payments.edit",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.view", "finance.create", "finance.edit", "finance.submit", "finance.approve",
    "settings.view",
    "workflow.view", "workflow.create",
    "suppliers.view", "suppliers.create",
    "staff.view",
    "leave.view", "leave.create",
  ],
  MKT: [
    "dashboard.view",
    "leads.view", "leads.create", "leads.edit",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
  ],
  HCNS: [
    "dashboard.view",
    "staff.view", "staff.create", "staff.edit",
    "leave.view", "leave.create", "leave.approve",
    "payroll.view", "payroll.create", "payroll.edit",
    "finance.create", "finance.submit",
    "settings.view",
    "workflow.view", "workflow.create",
    "contracts.view", "contracts.create", "contracts.edit",
    "payments.view",
    "suppliers.view",
  ],
  SALE_DOMESTIC: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  SALE_INBOUND: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  SALE_OUTBOUND: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  SALE_MICE: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create", "leads.edit",
    "bookings.view", "bookings.create",
    "quotations.view", "quotations.create", "quotations.edit",
    "contracts.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  TOUR: [
    "dashboard.view",
    "customers.view",
    "bookings.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
  ],
  INTERN_SALE_DOMESTIC: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  INTERN_SALE_OUTBOUND: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  INTERN_SALE_MICE: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  INTERN_SALE_INBOUND: [
    "dashboard.view",
    "customers.view", "customers.create", "customers.edit",
    "leads.view", "leads.create",
    "bookings.view", "bookings.create",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
    "raw_contacts.view", "raw_contacts.create", "raw_contacts.edit",
  ],
  INTERN_DIEUHAN: [
    "dashboard.view",
    "bookings.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
  ],
  INTERN_MKT: [
    "dashboard.view",
    "leads.view", "leads.create", "leads.edit",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
  ],
  INTERN_HCNS: [
    "dashboard.view",
    "staff.view",
    "leave.view", "leave.create",
    "workflow.view",
    "payroll.view",
  ],
  INTERN_KETOAN: [
    "dashboard.view",
    "bookings.view",
    "payments.view",
    "leave.view", "leave.create",
    "workflow.view",
    "staff.view",
    "payroll.view",
  ],
};

export function getDefaultPermissions(role: string): PermissionKey[] {
  return DEFAULT_PERMISSIONS[role] || [];
}

// Re-export from context - this is now the main hook
export function usePermissions() {
  return usePermissionsContext();
}
