ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_type_check;

ALTER TABLE public.notifications ADD CONSTRAINT notifications_type_check
CHECK (type IN (
  'birthday','company_anniversary','follow_up','payment_due','contract_expiry','internal_note',
  'LEAD_FORGOTTEN','FOLLOW_UP_OVERDUE','TRAVEL_DATE_NEAR',
  'mention','system','reminder',
  'BOOKING_DEPARTURE_NEAR','PAYMENT_DUE','CONTRACT_APPROVAL_OVERDUE','QUOTATION_NO_RESPONSE',
  'EMPLOYEE_BIRTHDAY','EMPLOYEE_CONTRACT_EXPIRING',
  'ESCALATION_LV1','ESCALATION_LV2','ESCALATION_LV3',
  'LEAVE_REQUEST_NEW','LEAVE_REQUEST_RESULT',
  'BUDGET_ESTIMATE_NEW','BUDGET_ESTIMATE_RESULT',
  'BUDGET_SETTLEMENT_STATUS','BUDGET_SETTLEMENT_CLOSED','BUDGET_SETTLEMENT_REJECTED',
  'TRANSACTION_APPROVAL','TRANSACTION_APPROVED','TRANSACTION_REJECTED'
));