ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check
  CHECK (role = ANY (ARRAY[
    'ADMIN', 'SUPER_ADMIN', 'DIRECTOR', 'HCNS', 'KETOAN',
    'MANAGER', 'DIEUHAN',
    'SALE_DOMESTIC', 'SALE_INBOUND', 'SALE_OUTBOUND', 'SALE_MICE',
    'TOUR', 'MKT', 'INTERN'
  ]));